def Username_xpath(): return "//p[@class='oxd-text oxd-text--p'][1]"
def Password_xpath(): return "//p[@class='oxd-text oxd-text--p'][2]"
def username_textbox(): return "//input[@name='username']"
def password_textbox(): return "//input[@name='password']"
def submit_button(): return "//button[@type='submit']"
def my_info(): return "//span[text()='My Info']"
def middle_name(): return "//input[@name='middleName']"
def Save_PD(): return "(//button[@type='submit'])[1]"
def logout_1(): return "//i[@class='oxd-icon bi-caret-down-fill oxd-userdropdown-icon']"
def logout_2(): return "//a[text()='Logout']"
def Leave_button(): return "//span[text()='Leave']"
def Apply_button(): return "//a[text()='Apply']"
def Leave_type_drop_down(): return "//div[@class='oxd-select-text--after']"
def Leave_type_CAN_F(): return "//div[contains(@class,'oxd-select-dropdown')]//div[2]"
def fromDate(): return "(//div[@class='oxd-date-input']/input)[1]"
def applyButton(): return "//button[@class='oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space']"
def comment(): return "//textarea[@class='oxd-textarea oxd-textarea--active oxd-textarea--resize-vertical']"
def My_Leave(): return "//a[text()='My Leave']"
def Canel_leave(): return "//div[@class='oxd-table-row']//div[text()='Travelling 1']/ancestor::div[@role='row']//button[contains(., 'Cancel')]"
def Recruitment(): return "//span[text()='Recruitment']"
def Vacancies(): return "//a[text()='Vacancies']"
def Total_record_count(): return "//span[@class='oxd-text oxd-text--span']"
def Table_xpath(): return "//div[@class='oxd-table-body']"
def Column_xpath(): return ".//div[@role='cell']"
def Row_xpath(): return ".//div[@role='row']"